project:
  type: website
  output-dir: docs

resources:
  - scorm  # Specify the relative path to your SCORM folder
  - SCORM_API_wrapper.js # to simulate the LMS API requested by scorm pkg

format: 
  html:
    page-layout: full
    theme: cosmo
    css: style.css
    smooth-scroll: true
    code-annotations: hover
    title-block-banner: true
    toc: false
    code-fold: true
    code-summary: "Code"
    fontawesome: true  # Enable Font Awesome icons

website:
  reader-mode: false
  open-graph: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024 || UNU-MERIT Capacity Development Office" 
    right: 
      - icon: github
        href: https://github.com/CapacityDevelopmentOffice
      - icon: building 
        href: https://unu.edu/merit 

  # Define the logo directly in the navbar section
  navbar:
    logo: images/logo.png
    right:
      - href: index.qmd
        icon: globe
        text: "Home"
      - href: networks.qmd
        icon: share
        text: "Economic Networks"
      - href: policytoolkit.qmd
        icon: briefcase
        text: "Policy Toolkit"
      - href: ml4pp.qmd
        icon: robot
        text: "Machine Learning for Policy"





