project:
  type: website

website:
  reader-mode: true
  open-graph: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024 || UNU-MERIT Capacity Development Office" 
    right: 
      - icon: github
        href: https://github.com/michelleg06/
      - icon: building 
        href: https://unu.edu/merit 

  title: "CDO"
  navbar:
    right:
      - href: index.qmd
        icon: globe
        text: "Home"
      - href: networks.qmd
        icon: share
        text: "Economic Networks"


    

format:
  html:
    theme: cosmo
    css: style.css
    smooth-scroll: true
    code-annotations: hover
    title-block-banner: true
    toc: false
    #toc-location: left
    #toc-title: " "
    code-fold: true
    code-summary: "Code"
    fontawesome: true  # Enable Font Awesome icons
    #includes:
    #  after_body: footer.html  # Correct indentation here


output_dir: "."  # if publishing on Github pages
